### ISSUE TITLE
Eager to try this libary

### ISSUE THREAD

**Issue by hausofpayne17** [GoergPflug/AttinyStreamGfxApi#5]
Hi Goerg:

Thanks for this library. I'm a high school teacher and looking for a light footprint OLED graphics library for my students to do their Arduino projects. Your library sounds very encouraging!

I'm trying to run the 'arduino_text_scroll_example' from your library.

I've tried to compile on both a standard Arduino Nano and an ATTiny85.

I took out the '/dev/' prefixes for the tiny_multi_os.h and displayfunc.h files.

But now when I compile on an ATTiny85, I get:
/////////////////////
In file included from C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:48:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h: In function 'Display':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:531:48: error: 'SECOND_CONSOLE_LINE_LENGTH' undeclared (first use in this function); did you mean 'SECOND_CONSOLE_LINE_END'?
     u8 the_char = (screen2[charpos_second_con +SECOND_CONSOLE_LINE_LENGTH* (((second_console_y>>8)-SECOND_CONSOLE_LINE_START)>>3)]);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                SECOND_CONSOLE_LINE_END
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:531:48: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c: In function 'MainTask':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:77:4: error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,zoom,zoom);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21: note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13: note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:79:4: error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,256,zoom);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21: note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13: note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:81:4: error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,zoom,256);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21: note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13: note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
exit status 1
Error compiling for board ATtiny25/45/85.
//////////

I have no real idea how to fix this issue or set things so I can compile and run this basic sketch.

Any suggestions you an offer are appreciated.

Thanks again for this promising library.

Respectfully,

Gord Payne
Ontario, Canada

**Comment by GoergPflug** [comment]
oops thats a bug, in fact its two bugs, the example you used is outdated, i deleted it, it is for the arduino ide on the attiny85 without using arduino libraries.... use "text scroll for arduino using wire" instead, and then there was a second bug that caused this correct sample to show a glitch. 
On the Attiny85 the Library is only tested in microchip studio, the arduino versions of the library should work on the attiny85, but i have not tested them using the arduino ide.


i deleted the sample because it is higly confusing, and fixed the library and the correct sample, it showed a glitch at the right side of the screen, i made a mistake when i implemented background rotation.

i tested it on my arduino mega 2560, and on the wokwi online emulator:
https://wokwi.com/projects/330194386855920210 <---here


for testing i also ported the background rotation sample to ardunio.

thank you for your bug report :-)

**Comment by hausofpayne17** [comment]
Hi Georg:

Thanks for the fast reply.

Still getting issue. I'm using 1.8.16 Arduino IDE.

I tried the using_wire version of the sketch. I removed the /dev/
references in the sketch and removed /dev/ prefixes from textzoom.c file.

Any suggestions are welcome.

/////////////////////
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:35:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_sda_release':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:194:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR |= 0x80;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:194:2:
note: each undeclared identifier is reported only once for each function it
appears in
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_sda_low':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:199:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR &= ~0x80;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_start':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:210:2:
error: 'USISR' undeclared (first use in this function); did you mean 'SPSR'?
  USISR = _BV(USISIF);
  ^~~~~
  SPSR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:210:14:
error: 'USISIF' undeclared (first use in this function); did you mean
'USISR'?
  USISR = _BV(USISIF);
              ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:35:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_stop':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:222:2:
error: 'USISR' undeclared (first use in this function); did you mean 'SPSR'?
  USISR = _BV(USIPF);
  ^~~~~
  SPSR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:222:14:
error: 'USIPF' undeclared (first use in this function); did you mean
'USISR'?
  USISR = _BV(USIPF);
              ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:45:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_sda_release':
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:35:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_write_byte':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:232:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR = byte;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:233:2:
error: 'USISR' undeclared (first use in this function); did you mean
'USIDR'?
  USISR = 7;
  ^~~~~
  USIDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:194:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR |= 0x80;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:194:2:
note: each undeclared identifier is reported only once for each function it
appears in
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:237:3:
error: 'USICR' undeclared (first use in this function); did you mean
'USISR'?
   USICR |= _BV(USICLK);
   ^~~~~
   USISR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:237:16:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
   USICR |= _BV(USICLK);
                ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_sda_low':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:199:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR &= ~0x80;
  ^~~~~
  SPDR
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:35:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_init':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:2:
error: 'USICR' undeclared (first use in this function); did you mean 'SPCR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
  ^~~~~
  SPCR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_start':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:210:2:
error: 'USISR' undeclared (first use in this function); did you mean 'SPSR'?
  USISR = _BV(USISIF);
  ^~~~~
  SPSR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:210:14:
error: 'USISIF' undeclared (first use in this function); did you mean
'USISR'?
  USISR = _BV(USISIF);
              ^
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:14:
error: 'USIWM1' undeclared (first use in this function); did you mean
'USICR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
              ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:45:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_stop':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:222:2:
error: 'USISR' undeclared (first use in this function); did you mean 'SPSR'?
  USISR = _BV(USIPF);
  ^~~~~
  SPSR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:28:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
                            ^
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:222:14:
error: 'USIPF' undeclared (first use in this function); did you mean
'USISR'?
  USISR = _BV(USIPF);
              ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:45:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_write_byte':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:232:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR = byte;
  ^~~~~
  SPDR
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:35:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'one_i2c_bit_byte':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:337:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR = byte;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:233:2:
error: 'USISR' undeclared (first use in this function); did you mean
'USIDR'?
  USISR = 7;
  ^~~~~
  USIDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:338:2:
error: 'USISR' undeclared (first use in this function); did you mean
'USIDR'?
  USISR = 7;
  ^~~~~
  USIDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:237:3:
error: 'USICR' undeclared (first use in this function); did you mean
'USISR'?
   USICR |= _BV(USICLK);
   ^~~~~
   USISR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'one_i2c_bit_1':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:353:2:
error: 'USICR' undeclared (first use in this function); did you mean 'SPCR'?
  USICR |= _BV(USICLK);
  ^~~~~
  SPCR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:237:16:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
   USICR |= _BV(USICLK);
                ^
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\alien.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:353:15:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
  USICR |= _BV(USICLK);
               ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:45:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'os_i2c_init':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:2:
error: 'USICR' undeclared (first use in this function); did you mean 'SPCR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
  ^~~~~
  SPCR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:14:
error: 'USIWM1' undeclared (first use in this function); did you mean
'USICR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
              ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:252:28:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
  USICR = _BV(USIWM1) | _BV(USICLK);
                            ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:45:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'one_i2c_bit_byte':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:337:2:
error: 'USIDR' undeclared (first use in this function); did you mean 'SPDR'?
  USIDR = byte;
  ^~~~~
  SPDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:338:2:
error: 'USISR' undeclared (first use in this function); did you mean
'USIDR'?
  USISR = 7;
  ^~~~~
  USIDR
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:
In function 'one_i2c_bit_1':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:353:2:
error: 'USICR' undeclared (first use in this function); did you mean 'SPCR'?
  USICR |= _BV(USICLK);
  ^~~~~
  SPCR
In file included from c:\program files
(x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:1:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\tiny_multi_os.h:353:15:
error: 'USICLK' undeclared (first use in this function); did you mean
'USICR'?
  USICR |= _BV(USICLK);
               ^
In file included from
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:48:0:
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:
In function 'Display':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:445:25:
error: 'SECOND_CONSOLE_LINE_LENGTH' undeclared (first use in this
function); did you mean 'SECOND_CONSOLE_LINE_END'?

 if(charpos_second_con>SECOND_CONSOLE_LINE_LENGTH)charpos_second_con=SECOND_CONSOLE_LINE_LENGTH-1;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
                         SECOND_CONSOLE_LINE_END
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:
In function 'MainTask':
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:77:4:
error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,zoom,zoom);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21:
note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13:
note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:79:4:
error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,256,zoom);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21:
note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13:
note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:81:4:
error: too few arguments to function 'Display'
    Display(0, 0, 0,console,console2,zoom,256);
    ^~~~~~~
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\textzoom.c:23:21:
note: declared here
 #define DISPLAYFUNC Display
                     ^
C:\Users\HP3\Documents\Arduino\libraries\AttinyStreamGfxApi-main\displayfunc.h:356:13:
note: in expansion of macro 'DISPLAYFUNC'
 static void DISPLAYFUNC (
             ^~~~~~~~~~~
exit status 1
Error compiling for board Arduino Nano.



//////////////

**Comment by GoergPflug** [comment]
i am not certain if you are doing the right thing, the library is "cross platform", it supports:
attiny85 using microchip studio and a custom i2c library, attiny85 using arduno using custom i2c,
and arduino using wire.

actually the "using wire" versions also work on the attiny85, without wire, just by removing "#include <wire" and #define ENABLE_WIRE


i looks like you are compiling the c-versions of the examples in arduino, this will not work because arduino does not support embedded-c, only c++. (but i am not certain, maybe its a bug or incompatibility, i am using ardunino 1.8.19)

i attached a zip file for the text scoll example, this should work out of the box on arduino (i tested it on my mega2560)

extract this file to a directory named "text_scroll"

open the text_scroll.ino file with the arduino ide, compile and upload. #includes do not need to be changed because the two .h files are also included.

if you want to compile for attiny85 instead of your arduino board:
remove the first two lines:

#include <Wire.h>
#define ENABLE_WIRE

i hope that helps (i need to write a usage manual)


 
[text_scroll.zip](https://github.com/GoergPflug/AttinyStreamGfxApi/files/8584093/text_scroll.zip)

**Comment by hausofpayne17** [comment]
Hi Georg:

The text_scroll sketch you sent DOES WORK! Very fast and unreadable and dim. I'm using a 128x64 OLED display. I guess your sketch is for different dimensions?

I opened the alien_arduino_port sketch, the real .ino file and it still gives those DISPLAYFUNC errors when compiled on the Nano.

**Comment by GoergPflug** [comment]
i also use a 128x64 display, but there are different ways to initalize the display, i switched the init sequence to different values, and now it is much brighter at my place, maybe it was always to dark ....

could you please test this version of the alien sample and tell me if the brightness is ok, if so i will update the main version


all samples are a bit faster than in the videos because i improved speed in the last two versions (just call wait_ms to slow it down).


[alien_arduino_port.zip](https://github.com/GoergPflug/AttinyStreamGfxApi/files/8584528/alien_arduino_port.zip)

**Comment by GoergPflug** [comment]
i updated that in the main version, the new init-sequence is much better brightness wise.

**Comment by hausofpayne17** [comment]
Hi Georg:

See the attached screen shot

Just the top 12 lines are animating very quickly right to left. The bottom
diagonal lines are an artifact of the previous sketch running from a
standard u8glib graphicsTest demo sketch.

I will note that my display is probably an SH1106 display driver. Does that
matter with your library? I don't think it's an SSD1306. When I specify
that driver object, I don't get the whole display filling in that u8glib
demo.

**Comment by GoergPflug** [comment]
unfortunatly that does matter, the sh1106 does not support vertical mode, and my library depends on that mode. but you definiatly found a bug in the init sequence.... (your image seems to be missing, but i guess it is filling the top 8 pixel row over and over again)... did the text scroll fill the whole screen?

**Comment by hausofpayne17** [comment]
Thanks for your investigations Georg. Good to know. May want to note that
on your repository somewhere for users wanting to download it.

The SH1106 is the really cheap OLED that's very popular on aliExpress, ebay
etc.

Thanks again for your work on this library. I'll try it again when I get my
hands on an SSD1306.

Best wishes,

Gord

**Comment by GoergPflug** [comment]
yes i will add a note thank you for your time, you helped me fix two bugs :-)
